services:
  - type: web
    name: django-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "gunicorn myproject.wsgi:application --bind 0.0.0.0:8000"
    envVars:
      - key: GIS_KEY
        value: ${GIS_KEY}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
    autoDeploy: true
