services:
  - type: web
    name: django-app
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    envVars:
      - key: GIS_KEY
        value: ${GIS_KEY}
      - key: SECRET_KEY
        value: ${SECRET_KEY}
    autoDeploy: true
